export const CLOUD_ACCOUNTS_MOCK = [ {
  name: 'nick-DO-acc',
  provider: 'digitalocean',
  credentials: {
    accessToken: 'xxx',
    publicKey: 'xxx',
  },
}, {
  name: 'nick-aws-CA',
  provider: 'aws',
  credentials: { 'access_key': 'xxx', 'secret_key': 'xxx' },
}, {
  'name': 'nick-googl-CA', 'provider': 'gce', 'credentials': {
    auth_provider_x509_cert_url: 'https://www.googleapis.com/oauth2/v1/certs',
    auth_uri: 'https://accounts.google.com/o/oauth2/auth',
    client_email: 'test@test.iam.gserviceaccount.com',
    client_id: '1234',
    client_x509_cert_url: 'https://www.googleapis.com/robot/v1/metadata/x509/test-268%40ordinal-case-222023.iam.gserviceaccount.com',
    private_key: 'xxx',
    private_key_id: 'xxx',
    project_id: 'ordinal-case-test',
    token_uri: 'https://oauth2.googleapis.com/token',
    type: 'service_account',
  },
} ];


export const CLUSTERS_LIST_MOCK = [
  {
    'id': '768b61d5',
    'state': 'operational',
    'name': 'asdf',
    'provider': 'digitalocean',
    'rbacEnabled': true,
    'accountName': 'nick-DO-acc',
    'region': 'fra1',
    'zone': '',
    'apiPort': '',
    'auth': {
      'username': 'root',
      'token': '1234',
      'caKey': 'xxx',
      'caCert': 'xxx',
      'adminCert': 'xxx',
      'adminKey': 'xxx',
    },
    'sshUser': 'root',
    'sshKey': 'xxx',
    'bootstrapPublicKey': 'xxx',
    'bootstrapPrivateKey': 'xxx',
    'user': 'root',
    'password': '1234',
    'arch': 'amd64',
    'operatingSystem': 'linux',
    'operatingSystemVersion': 'xenial',
    'dockerVersion': '18.06.3',
    'K8SVersion': '1.13.4',
    'helmVersion': '2.11.0',
    'networking': {
      'manager': '0.10.0',
      'version': '0.10.0',
      'type': 'vxlan',
      'cidr': '10.0.0.0/16',
    },
    'subnets': null,
    'cloudSpec': {},
    'masters': {
      'asdf-master-862c': {
        'id': '122919495',
        'taskId': 'xxx',
        'role': 'master',
        'createdAt': 0,
        'provider': 'digitalocean',
        'region': 'fra1',
        'size': '1gb',
        'publicIp': '68.183.214.160',
        'privateIp': '10.135.8.93',
        'state': 'active',
        'name': 'asdf-master-862c',
      },
    },
    'nodes': {
      'asdf-node-8ba6': {
        'id': '122919912',
        'taskId': '8ba6410f-1f3f-495c-915f-bbf914bc5723',
        'role': 'node',
        'createdAt': 0,
        'provider': 'digitalocean',
        'region': 'fra1',
        'size': '1gb',
        'publicIp': '142.93.163.205',
        'privateIp': '10.135.124.182',
        'state': 'active',
        'name': 'asdf-node-8ba6',
      },
    },
    'tasks': [
      '768b61d5-229b-4667-879e-5720807c8522',
    ],
  },
];
