package templates

var Default = map[string]string{
	"add_authorized_keys":        addAuthorizedKeysTpl,
	"bootstrap_token":            bootstrapTokenTpl,
	"certificates":               certificatesTpl,
	"clustercheck":               clustercheckTpl,
	"cni":                        cniTpl,
	"dashboard":                  dashboardTpl,
	"docker":                     dockerTpl,
	"download_kubernetes_binary": downloadKubernetesBinaryTpl,
	"drain":                      drainTpl,
	"kubeadm":                    kubeadmTpl,
	"kubelet":                    kubelet,
	"network":                    networkTpl,
	"poststart":                  poststartTpl,
	"prometheus":                 prometheusTpl,
	"storageclass":               storageclassTpl,
	"tiller":                     tillerTpl,
	"upgrade":                    upgradeTpl,
	"evacuate":                   evacuateTpl,
	"uncordon":                   uncordonTpl,
	"apply":                      applyTpl,
	"install_app":                installApp,
}
